name: Build Triton wheels

inputs:
  python_version:
    required: true
    type: string

  ref:
    default: main
    type: string

  repository:
    default: triton-lang/triton
    type: string

runs:
  using: "composite"

  steps:
    - name: Build wheels
      shell: bash
      run: .ci/build-triton.sh "$PWD" "${{ inputs.repository }}" "${{ inputs.ref }}" "${{ inputs.python_version }}"

    - name: Repackage wheels
      shell: bash
      run: .ci/common/repackage-wheels.sh "$PWD"
      env:
        WHEEL_HOUSE: "dist/*.whl"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: triton_pascal-${{ inputs.python_version }}
        path: dist/*.whl
