name: "[R] Build vLLM (main)"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build vLLM wheels
        uses: ./.github/actions/build-vllm
        with:
          ghcr_token: ${{ secrets.GHCR_TOKEN }}
          ref: main

  publish:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish wheels
        uses: ./.github/actions/publish-wheels
        with:
          prefix: vllm_pascal-999.999.999

  update-index:
    needs: publish
    secrets: inherit
    uses: ./.github/workflows/zz-update-index.yml

    permissions:
      id-token: write
      pages: write

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:
